name: "Yutampo2MQTT HA Addon"
version: "3.2.3"  
slug: "yutampo2mqtt"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet avec automation interne"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true

options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300  
  setpoint: 50.0  
  default_hottest_hour: 15.0
  log_level: "DEBUG"
  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"

schema:
  username: str
  password: password
  scan_interval: int
  setpoint: float(30,60)  # Plage valide : 30°C à 60°C
  discovery_prefix: str?  # Optionnel
  weather_entity: str?  # Optionnel
  default_hottest_hour: float(0,23)
  log_level: list(VERBOSE|DEBUG|INFO|WARNING|ERROR)
  mqtt_host: str
  mqtt_port: str
  mqtt_user: str
  mqtt_password: str

map:
  - addon_config:rw
mqtt: true