name: "Yutampo HA Addon"
version: "1.1.8"
slug: "yutampo_ha_addon"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true

options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300

  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"
schema:
  username: str
  password: password
  scan_interval: int
map:
  - addon_config:rw
mqtt: true
