name: "Yutampo HA Addon"
version: "1.1.6"
slug: "yutampo_ha_addon"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true
environment: 
  - MQTT_HOST
  - MQTT_PORT
  - MQTT_USERNAME
  - MQTT_PASSWORD
options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300
schema:
  username: str
  password: password
  scan_interval: int
map:
  - addon_config:rw
mqtt: true
