name: "Yutampo2MQTT HA Addon"
version: "3.1.5"
slug: "yutampo2mqtt"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true

options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300

  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"
  
schema:
  username: str
  password: password
  scan_interval: int
  mqtt_host: str
  mqtt_port: str
  mqtt_user: str
  mqtt_password: str
  
map:
  - addon_config:rw
mqtt: true
