name: "Yutampo2MQTT HA Addon"
version: "2.1.4"
slug: "yutampo2mqtt"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet avec automation interne"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true

options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300
  discovery_prefix: "homeassistant"
  weather_entity: "weather.forecast_maison"
  log_level: "DEBUG"  # Valeurs autorisées : VERBOSE, DEBUG, INFO, WARNING, ERROR
  presets:
    - name: "Hiver"
      target_temperature: 50
      target_temperature_low: 45
      target_temperature_high: 55
      duration: 5.0
      hottest_hour: 14.0
    - name: "Printemps/Automne"
      target_temperature: 46
      target_temperature_low: 44
      target_temperature_high: 52
      duration: 6.0
      hottest_hour: 15.0
    - name: "Été"
      target_temperature: 46
      target_temperature_low: 41
      target_temperature_high: 51
      duration: 8.0
      hottest_hour: 16.0
  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"

schema:
  username: str
  password: password
  scan_interval: int
  discovery_prefix: str
  weather_entity: str
  log_level: str  # Validation dans le code : VERBOSE, DEBUG, INFO, WARNING, ERROR
  presets:
    - name: str
      target_temperature: float
      target_temperature_low: float
      target_temperature_high: float
      duration: float
      hottest_hour: float(0,23)?  # Optionnel, entre 0 et 23h
  mqtt_host: str
  mqtt_port: str
  mqtt_user: str
  mqtt_password: str

map:
  - addon_config:rw
mqtt: true