name: "Yutampo2MQTT HA Addon"
version: "1.0"
slug: "yutampo2mqtt"
description: "Add-on pour intégrer le chauffe-eau Yutampo via CSNet avec automation interne"
services:
  - mqtt:need
arch:
  - amd64
  - armv7
  - aarch64
init: false
boot: "auto"
homeassistant_api: true
hassio_api: true

options:
  username: "ton_username"
  password: "ton_password"
  scan_interval: 300
  presets:
    - name: "Hiver"
      target_temperature: 50
      target_temperature_low: 45
      target_temperature_high: 55
      duration: 6
    - name: "Printemps/Automne"
      target_temperature: 45
      target_temperature_low: 41
      target_temperature_high: 49
      duration: 5
    - name: "Été"
      target_temperature: 40
      target_temperature_low: 37
      target_temperature_high: 43
      duration: 4
  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"

schema:
  username: str
  password: password
  scan_interval: int
  presets:
    - name: str
      target_temperature: float
      target_temperature_low: float
      target_temperature_high: float
      duration: float
  mqtt_host: str
  mqtt_port: str
  mqtt_user: str
  mqtt_password: str

map:
  - addon_config:rw
mqtt: true