# ESP-12E WeMos D1 UNO R3 CH340 CH340G WiFi Development Board Based ESP8266 Shield Smart Electronic PCB For Arduino Compatible IDE

esphome:
  name: esp8266-relais
  

esp8266:
  board: d1

# Configuration WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  

  ap:
    ssid: "WeMosD1-Fbck-Hotspot"
    password: !secret ota_pwd

# Active le logging
logger:
  level: DEBUG
# Active l'API pour Home Assistant
api:

# Active le mode OTA (mise à jour à distance)
ota:
  - platform: esphome
    password: !secret ota_pwd

time:
  platform: homeassistant
  id: ha_time

mqtt:
  broker: !secret broker
  username: "yutampo_esp"
  password: !secret mqtt_password
  discovery: true

# Configuration des relais
#Broche D5 du PCB → GPIO14
#Broche D6 du PCB → GPIO12
#Broche D7 du PCB → GPIO13
#Broche D8 du PCB → GPIO15
switch:
  - platform: gpio
    name: "Limit electricity consumption"
    pin: GPIO14     # Broche 5 du PCB
    id: yutampo_esp_input_3
    # Inversé car les relais sont souvent actifs à l'état bas
    inverted: true

  - platform: gpio
    name: "Force DHW"
    pin: GPIO12     # Broche 6 du PCB
    id: yutampo_esp_input_2
    inverted: true



